app:
  name: Products
  description: This ${products} app provide apis for fetch,insert products from mongo products Collection.
server:
  port: 8082

spring:

  data:
    mongodb:
      host: localhost
      port: 27017
      database: products_db

    cache:
      type: redis
      redis:
        cache-null-values: true
        time-to-live: 40000
        port : 6379